apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app: loki
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory  # or change to persistent store (like consul/etcd) for multi-ingester setups
      replication_factor: 1
      path_prefix: /loki  # Store tokens and WAL in /loki for persistence

    schema_config:
      configs:
      - from: 2020-05-15
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

    storage_config:
      filesystem:
        directory: /loki/chunks

    ingester:
      wal:
        enabled: true
        dir: /loki/wal
      lifecycler:
        ring:
          kvstore:
            store: inmemory  # Can be consul/etcd in a distributed setup
          replication_factor: 1
        final_sleep: 0s
