apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'go-app'
        static_configs:
          - targets: ['go-app-service:8080']
            labels:
              service: 'go-app'
