apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  labels:
    app: promtail
spec:
  selector:
    app: promtail
  ports:
    - name: http
      protocol: TCP
      port: 9080 # Exposing the HTTP port
      targetPort: 9080
  type: ClusterIP # This will expose Promtail only within the cluster. Use 'NodePort' or 'LoadBalancer' for external access.
